// Exercise the real gallery against Three.js geometry with a minimal host.
// WebGL pixels and native pointer-lock UX still require explicit browser QA.
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import * as Three from '../assets/vendor/three.module.min.js';
let pending=null,activeRenderer,revoked=0,copies=0;
class Element{
 constructor(){this.listeners={};this.attrs={};this.dataset={};this.clientWidth=1200;this.clientHeight=750;this.width=1200;this.height=750;this.hidden=false;this.disabled=false;this.children=[];this.classList={toggle(){}}}
 addEventListener(type,fn){(this.listeners[type]??=[]).push(fn)} fire(type,values={}){for(const fn of this.listeners[type]||[])fn({preventDefault(){},...values})}
 setAttribute(k,v){this.attrs[k]=v}querySelector(s){return this.children.find(e=>e.selector===s)}querySelectorAll(){return []}getBoundingClientRect(){return{left:0,top:0,width:1200,height:750}}
 focus(){}setPointerCapture(){}remove(){this.removed=true}close(){this.open=false}showModal(){this.open=true}requestPointerLock(){doc.pointerLockElement=this;doc.fire('pointerlockchange')}
 getContext(){return{fillRect(){},fillText(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},drawImage(){copies++}}}toBlob(fn){fn({type:'image/png'})}
}
const host=new Element(),elements=new Map();for(const id of ['#spatial-status','#spatial-motion','#spatial-rain','#spatial-reset','#spatial-capture','#spatial-photo','#spatial-help'])elements.set(id,new Element());
const caption=new Element();caption.children=['span','p'].map(selector=>Object.assign(new Element(),{selector}));elements.set('.spatial-label',caption);const dialog=elements.get('#spatial-photo');dialog.children=['img','a[download]','button'].map(selector=>Object.assign(new Element(),{selector}));
const views=['lobby','hall','land','bridge','porter'].map(view=>Object.assign(new Element(),{dataset:{view}}));const modes=['cinema','fps'].map(controlMode=>Object.assign(new Element(),{dataset:{controlMode}}));const pads=['w','a','s','d','q','e'].map(move=>Object.assign(new Element(),{dataset:{move}}));
host.querySelector=s=>elements.get(s);host.querySelectorAll=s=>s==='[data-view]'?views:s==='[data-control-mode]'?modes:s==='[data-move]'?pads:[];host.prepend=el=>host.canvas=el;
const doc=new Element();doc.createElement=()=>new Element();doc.hidden=false;doc.fonts={ready:Promise.resolve()};doc.pointerLockElement=null;doc.exitPointerLock=()=>{doc.pointerLockElement=null;doc.fire('pointerlockchange')};
class Renderer{constructor(){activeRenderer=this;this.domElement=new Element();this.shadowMap={}}setPixelRatio(){}setSize(){}render(scene,camera){this.scene=scene;this.camera=camera}dispose(){this.disposed=true}}
class Controls{constructor(camera){this.camera=camera;this.target=new Three.Vector3();this.enabled=true}update(){if(this.enabled)this.camera.lookAt(this.target);return false}addEventListener(){}dispose(){}}
const win=new Element(),ctx=vm.createContext({T:{...Three,WebGLRenderer:Renderer},OrbitControls:Controls,devicePixelRatio:1,matchMedia:()=>({matches:false}),document:doc,window:win,AbortController,ResizeObserver:class{observe(){}disconnect(){}},requestAnimationFrame:fn=>(pending=fn,1),cancelAnimationFrame:()=>pending=null,performance:{now:()=>0},URL:{createObjectURL:()=>'blob:test',revokeObjectURL:()=>revoked++},console});
const source=fs.readFileSync(new URL('../assets/spatial/gallery.js',import.meta.url),'utf8').replace(/^import .*;$/gm,'').replace('export function mount','function mount');vm.runInContext(source,ctx);const cleanup=ctx.mount(host);
let time=0;function frames(n=1,dt=1/60){for(let i=0;i<n;i++){time+=dt*1000;const f=pending;pending=null;f?.(time)}}function select(name){views.find(b=>b.dataset.view===name).fire('click');frames(160)}function setMode(name){modes.find(b=>b.dataset.controlMode===name).fire('click');frames()}
frames();const scene=activeRenderer.scene,camera=activeRenderer.camera,[lobby,pedestal,hall,world]=scene.children.filter(o=>o.type==='Group');assert(lobby.visible&&!world.visible);select('hall');assert(!lobby.visible&&world.visible&&hall.visible&&pedestal.visible);
const materials=[];world.traverse(o=>{if(o.material)materials.push(o.material)});const materialState=materials.map(m=>JSON.stringify(m.toJSON())),background=scene.background.getHex(),fog=[scene.fog.near,scene.fog.far,scene.fog.color.getHex()];select('land');const after=[];world.traverse(o=>{if(o.material)after.push(o.material)});assert.deepEqual(after,materials);assert.deepEqual(after.map(m=>JSON.stringify(m.toJSON())),materialState);assert.equal(scene.background.getHex(),background);assert.deepEqual([scene.fog.near,scene.fog.far,scene.fog.color.getHex()],fog);
// Cinema controls preserve one center point. W/S change radius; A/D and Q/E rotate around it.
const center=activeRenderer.camera.clone?null:null,target=ctx; // keep the VM opaque; infer the center from the look direction before movement.
const cinemaTarget=activeRenderer.camera.position.clone().add(activeRenderer.camera.getWorldDirection(new Three.Vector3()).multiplyScalar(13));const c0=camera.position.clone(),dir0=camera.getWorldDirection(new Three.Vector3());host.canvas.fire('keydown',{key:'w'});frames(60);win.fire('keyup',{key:'w'});const c1=camera.position.clone();assert(c1.distanceTo(cinemaTarget)<c0.distanceTo(cinemaTarget),'W pushes toward cinema center');
host.canvas.fire('keydown',{key:'a'});const beforeOrbit=camera.position.clone();frames(60);win.fire('keyup',{key:'a'});assert(camera.position.distanceTo(beforeOrbit)>1,'A orbits instead of translating');const orbitLook=camera.getWorldDirection(new Three.Vector3());assert(orbitLook.distanceTo(dir0)>.05,'orbit keeps re-aiming at center');
host.canvas.fire('keydown',{key:'e'});const beforeRise=camera.position.y;frames(30);win.fire('keyup',{key:'e'});assert(camera.position.y>beforeRise,'E raises cinema camera around center');
// First person uses a fixed 1.5m eye offset above its foot position and independent yaw/pitch.
setMode('fps');select('hall');const fpsStart=camera.position.clone(),fpsLook=camera.getWorldDirection(new Three.Vector3());host.canvas.fire('keydown',{key:'w'});assert.equal(camera.position.distanceTo(fpsStart),0);frames(60);win.fire('keyup',{key:'w'});const walked=camera.position.clone();assert(walked.distanceTo(fpsStart)>3&&Math.abs(walked.y-fpsStart.y)<.001,'W walks horizontally at eye height');
host.canvas.fire('keydown',{key:'d'});frames(45);win.fire('keyup',{key:'d'});assert(Math.abs(camera.position.y-walked.y)<.001,'D strafes without camera drift');const beforeQE=camera.position.y;host.canvas.fire('keydown',{key:'e'});frames(30);win.fire('keyup',{key:'e'});assert(camera.position.y>beforeQE+1,'E changes the foot level while preserving eye offset');
const lookBefore=camera.getWorldDirection(new Three.Vector3()),posBefore=camera.position.clone();host.canvas.fire('pointerdown',{clientX:500,clientY:350});host.canvas.fire('pointermove',{clientX:560,clientY:320});host.canvas.fire('pointerup',{clientX:560,clientY:320});assert(camera.position.distanceTo(posBefore)<.001&&camera.getWorldDirection(new Three.Vector3()).distanceTo(lookBefore)>.05,'mouse look rotates view without moving body');
// Mode switching clears held keys and disables auto orbit in first person.
host.canvas.fire('keydown',{key:'w'});setMode('cinema');const switched=camera.position.clone();frames(30);assert(camera.position.distanceTo(switched)<.001);assert.equal(elements.get('#spatial-motion').disabled,false);setMode('fps');assert.equal(elements.get('#spatial-motion').disabled,true);
select('land');elements.get('#spatial-capture').fire('click');await new Promise(r=>setImmediate(r));assert(dialog.open);assert.equal(dialog.querySelector('img').src,'blob:test');assert.match(dialog.querySelector('a[download]').download,/game-temple-land-\d+\.png/);assert.equal(copies,2);
cleanup();assert(activeRenderer.disposed&&host.canvas.removed&&!dialog.open);assert.equal(revoked,1);console.log(JSON.stringify({stateTransitions:'passed',materialIdentity:'passed',cinemaCenterControls:'passed',firstPersonControls:'passed',modeIsolation:'passed',captureLifecycle:'passed',webglPixels:'not tested'}));
