// Exercise the real gallery against Three.js geometry with a minimal host.
// WebGL pixels and native pointer-lock UX still require explicit browser QA.
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import * as Three from '../assets/vendor/three.module.min.js';
let pending=null,activeRenderer,revoked=0,copies=0,resizeCallback;
class Element{
 constructor(){this.listeners={};this.attrs={};this.dataset={};this.clientWidth=1200;this.clientHeight=750;this.width=1200;this.height=750;this.hidden=false;this.disabled=false;this.children=[];this.classList={toggle(){}}}
 addEventListener(type,fn){(this.listeners[type]??=[]).push(fn)} fire(type,values={}){for(const fn of this.listeners[type]||[])fn({preventDefault(){},...values})}
 setAttribute(k,v){this.attrs[k]=v}querySelector(s){return this.children.find(e=>e.selector===s)}querySelectorAll(){return []}getBoundingClientRect(){return{left:0,top:0,width:1200,height:750}}
 focus(){}setPointerCapture(){}remove(){this.removed=true}close(){this.open=false}showModal(){this.open=true}requestPointerLock(){doc.pointerLockElement=this;doc.fire('pointerlockchange')}
 getContext(){return{fillRect(){},fillText(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},drawImage(){copies++}}}toBlob(fn){fn({type:'image/png'})}
}
const host=new Element(),elements=new Map();for(const id of ['#spatial-status','#spatial-motion','#spatial-rain','#spatial-reset','#spatial-capture','#spatial-photo','#spatial-help','#spatial-home-view','#spatial-dof','#spatial-aperture','#spatial-focus','#spatial-focus-pick','#spatial-focus-value','#spatial-aperture-value','#spatial-focal','#spatial-focal-value','#spatial-aa','#spatial-ssr'])elements.set(id,new Element());
const caption=new Element();caption.children=['span','p'].map(selector=>Object.assign(new Element(),{selector}));elements.set('.spatial-label',caption);const dialog=elements.get('#spatial-photo');dialog.children=['img','a[download]','button'].map(selector=>Object.assign(new Element(),{selector}));
const views=['lobby','hall','land','bridge','porter','spider','west'].map(view=>Object.assign(new Element(),{dataset:{view}}));const modes=['cinema','fps'].map(controlMode=>Object.assign(new Element(),{dataset:{controlMode}}));const pads=['w','a','s','d','q','e'].map(move=>Object.assign(new Element(),{dataset:{move}}));
host.querySelector=s=>elements.get(s);host.querySelectorAll=s=>s==='[data-view]'?views:s==='[data-control-mode]'?modes:s==='[data-move]'?pads:[];host.prepend=el=>host.canvas=el;
const doc=new Element();doc.createElement=()=>new Element();doc.hidden=false;doc.fonts={ready:Promise.resolve()};doc.pointerLockElement=null;doc.exitPointerLock=()=>{doc.pointerLockElement=null;doc.fire('pointerlockchange')};
class Renderer{constructor(){activeRenderer=this;this.domElement=new Element();this.shadowMap={}}setPixelRatio(v){this.pixelRatio=v}setSize(w,h){this.size=[w,h]}getDrawingBufferSize(v){return v.set(1200,750)}setRenderTarget(t){this.target=t}render(scene,camera){if(camera.isPerspectiveCamera){this.scene=scene;this.camera=camera}this.renders=(this.renders||0)+1}dispose(){this.disposed=true}}
class Controls{constructor(camera){this.camera=camera;this.target=new Three.Vector3();this.enabled=true}update(){if(this.enabled)this.camera.lookAt(this.target);return false}addEventListener(){}dispose(){}}
const win=new Element(),ctx=vm.createContext({T:{...Three,WebGLRenderer:Renderer,TextureLoader:class{load(){return new Three.Texture()}}},OrbitControls:Controls,devicePixelRatio:1,matchMedia:()=>({matches:false}),document:doc,window:win,AbortController,ResizeObserver:class{constructor(fn){resizeCallback=fn}observe(){}disconnect(){}},requestAnimationFrame:fn=>(pending=fn,1),cancelAnimationFrame:()=>pending=null,performance:{now:()=>0},URL:class extends URL{static createObjectURL(){return 'blob:test'}static revokeObjectURL(){revoked++}},unusedURL:{createObjectURL:()=>'blob:test',revokeObjectURL:()=>revoked++},console});
const source=fs.readFileSync(new URL('../assets/spatial/gallery.js',import.meta.url),'utf8').replace(/^import .*;$/gm,'').replace('export function mount','function mount').replaceAll('import.meta.url',JSON.stringify('file:///workspace/gallery.js'));vm.runInContext(source,ctx);const cleanup=ctx.mount(host);
let time=0;function frames(n=1,dt=1/60){for(let i=0;i<n;i++){time+=dt*1000;const f=pending;pending=null;f?.(time)}}function select(name){views.find(b=>b.dataset.view===name).fire('click');frames(160)}function setMode(name){modes.find(b=>b.dataset.controlMode===name).fire('click');frames()}
elements.get('#spatial-focal').value='35';elements.get('#spatial-aperture').value='5.6';elements.get('#spatial-focus').value='18';
frames();const scene=activeRenderer.scene,camera=activeRenderer.camera,[lobby,pedestal,hall,world]=scene.children.filter(o=>o.type==='Group');assert(lobby.visible&&!world.visible);select('hall');assert(!lobby.visible&&world.visible&&hall.visible&&pedestal.visible);
const materials=[];world.traverse(o=>{if(o.material)materials.push(o.material)});const materialState=materials.map(m=>JSON.stringify(m.toJSON())),background=scene.background.getHex(),fog=[scene.fog.near,scene.fog.far,scene.fog.color.getHex()];select('land');const after=[];world.traverse(o=>{if(o.material)after.push(o.material)});assert.deepEqual(after,materials);assert.deepEqual(after.map(m=>JSON.stringify(m.toJSON())),materialState);assert.notEqual(scene.background.getHex(),background,'outdoor light and background differ');assert.notDeepEqual([scene.fog.near,scene.fog.far,scene.fog.color.getHex()],fog);assert(!hall.visible&&!pedestal.visible);assert(scene.children.find(g=>g.children.some(o=>o.geometry?.type==='CylinderGeometry')).visible,'far landscape appears');
// Geometry regression: real meshes must cover the exterior and share the diorama seam.
const outdoor=scene.children.find(g=>g.children.some(o=>o.geometry?.type==='CylinderGeometry'));
const extension=outdoor.children.find(o=>o.geometry?.attributes.color),original=world.children.find(o=>o.geometry?.attributes.color);
const originalPos=original.geometry.attributes.position,outerPos=extension.geometry.attributes.position;
const edgeVertices=[];for(let i=0;i<originalPos.count;i++)if(Math.abs(originalPos.getX(i))===12||Math.abs(originalPos.getZ(i))===10)edgeVertices.push(new Three.Vector3().fromBufferAttribute(originalPos,i));
for(const v of edgeVertices){let gap=Infinity;for(let i=0;i<368;i++)gap=Math.min(gap,v.distanceTo(new Three.Vector3().fromBufferAttribute(outerPos,i)));assert(gap<1e-5,'terrain seam is watertight');}
const normals=extension.geometry.attributes.normal;for(let i=0;i<normals.count;i++)assert(normals.getY(i)>0,'terrain normals face sky');
scene.updateMatrixWorld(true);const groundRay=new Three.Raycaster();
for(const x of [-75,-24,0,24,75])for(const z of [-65,-20,0,20,65]){if(Math.abs(x)<12&&Math.abs(z)<10)continue;groundRay.set(new Three.Vector3(x,80,z),new Three.Vector3(0,-1,0));assert(groundRay.intersectObject(extension).length,'exterior has modeled ground');}
for(const x of [-90,-30,-13,13,30,90]){const z=1.1*Math.sin(x*.36)+.4*Math.sin(x*.9);groundRay.set(new Three.Vector3(x,80,z),new Three.Vector3(0,-1,0));const hit=groundRay.intersectObject(extension)[0];assert(hit&&hit.point.y<1.24,'stream bed remains below water at '+x+': '+hit?.point.y);}
select('hall');assert(!outdoor.visible,'outer terrain is hidden in exhibition');select('land');
// Cinema controls preserve one center point. W/S change radius; A/D and Q/E rotate around it.
const center=activeRenderer.camera.clone?null:null,target=ctx; // keep the VM opaque; infer the center from the look direction before movement.
const cinemaTarget=activeRenderer.camera.position.clone().add(activeRenderer.camera.getWorldDirection(new Three.Vector3()).multiplyScalar(13));const c0=camera.position.clone(),dir0=camera.getWorldDirection(new Three.Vector3());host.canvas.fire('keydown',{key:'w'});frames(60);win.fire('keyup',{key:'w'});const c1=camera.position.clone();assert(c1.distanceTo(cinemaTarget)<c0.distanceTo(cinemaTarget),'W pushes toward cinema center');
host.canvas.fire('keydown',{key:'a'});const beforeOrbit=camera.position.clone();frames(60);win.fire('keyup',{key:'a'});assert(camera.position.distanceTo(beforeOrbit)>1,'A orbits instead of translating');const orbitLook=camera.getWorldDirection(new Three.Vector3());assert(orbitLook.distanceTo(dir0)>.05,'orbit keeps re-aiming at center');
host.canvas.fire('keydown',{key:'e'});const beforeRise=camera.position.y;frames(30);win.fire('keyup',{key:'e'});assert(camera.position.y>beforeRise,'E raises cinema camera around center');
select('hall');const standard=camera.position.clone();host.canvas.fire('keydown',{key:'q'});frames(240);win.fire('keyup',{key:'q'});assert(Math.abs(camera.position.y+.15)<.001,'cinema reaches floor without crossing it');elements.get('#spatial-home-view').fire('click');frames(200);assert(camera.position.distanceTo(standard)<.02,'standard view is repeatable');
// First person uses a fixed 1.5m eye offset above its foot position and independent yaw/pitch.
setMode('fps');select('hall');const fpsStart=camera.position.clone(),fpsLook=camera.getWorldDirection(new Three.Vector3());host.canvas.fire('keydown',{key:'w'});assert.equal(camera.position.distanceTo(fpsStart),0);frames(60);win.fire('keyup',{key:'w'});const walked=camera.position.clone();assert(walked.distanceTo(fpsStart)>3&&Math.abs(walked.y-fpsStart.y)<.001,'W walks horizontally at eye height');
host.canvas.fire('keydown',{key:'d'});frames(45);win.fire('keyup',{key:'d'});assert(Math.abs(camera.position.y-walked.y)<.001,'D strafes without camera drift');const beforeQE=camera.position.y;host.canvas.fire('keydown',{key:'e'});frames(30);win.fire('keyup',{key:'e'});assert(camera.position.y>beforeQE+1,'E changes the foot level while preserving eye offset');
const lookBefore=camera.getWorldDirection(new Three.Vector3()),posBefore=camera.position.clone();host.canvas.fire('pointerdown',{clientX:500,clientY:350});host.canvas.fire('pointermove',{clientX:560,clientY:320});host.canvas.fire('pointerup',{clientX:560,clientY:320});assert(camera.position.distanceTo(posBefore)<.001&&camera.getWorldDirection(new Three.Vector3()).distanceTo(lookBefore)>.05,'mouse look rotates view without moving body');
// Mode switching clears held keys and disables auto orbit in first person.
host.canvas.fire('keydown',{key:'w'});setMode('cinema');const switched=camera.position.clone();frames(30);assert(camera.position.distanceTo(switched)<.001);assert.equal(elements.get('#spatial-motion').disabled,false);setMode('fps');assert.equal(elements.get('#spatial-motion').disabled,true);
select('land');const beforeDof=activeRenderer.renders;elements.get('#spatial-dof').fire('click');frames();assert.equal(activeRenderer.renders-beforeDof,4,'scene, SSR, DOF and AA composite');elements.get('#spatial-aperture').value='0.95';elements.get('#spatial-aperture').fire('input');frames();elements.get('#spatial-focus').value='3';elements.get('#spatial-focus').fire('input');frames();assert.equal(elements.get('#spatial-focus-value').textContent,'3.0 m');elements.get('#spatial-dof').fire('click');const beforeDirect=activeRenderer.renders;frames();assert.equal(activeRenderer.renders-beforeDirect,3,'DOF off preserves SSR and AA');elements.get('#spatial-aa').fire('click');elements.get('#spatial-ssr').fire('click');const bypass=activeRenderer.renders;frames();assert.equal(activeRenderer.renders-bypass,1,'all effects off bypass postprocessing');const oldFov=camera.fov;elements.get('#spatial-focal').value='85';elements.get('#spatial-focal').fire('input');frames();assert(camera.fov<oldFov,'longer focal length narrows view');assert.equal(elements.get('#spatial-aperture-value').textContent,'F0.95');
setMode('cinema');select('land');for(const key of ['s','a','q']){host.canvas.fire('keydown',{key});frames(300);win.fire('keyup',{key});assert(Math.abs(camera.position.x)<=11.5&&Math.abs(camera.position.z)<=9.5&&camera.position.y<=14,'cinema confined to exhibit');}
setMode('fps');host.canvas.fire('keydown',{key:'s'});frames(500);win.fire('keyup',{key:'s'});assert(Math.abs(camera.position.x)<=11.5&&Math.abs(camera.position.z)<=9.5,'FPS confined to exhibit');
select('lobby');select('land');assert(lobby.visible&&!world.visible,'cannot skip from lobby to wilderness');select('hall');select('land');elements.get('#spatial-capture').fire('click');await new Promise(r=>setImmediate(r));assert(dialog.open);assert.equal(dialog.querySelector('img').src,'blob:test');assert.match(dialog.querySelector('a[download]').download,/game-temple-land-\d+\.png/);assert.equal(copies,2);
// New room lifecycles: independent real geometry, no duplicate builds, safe camera travel.
select('lobby');select('spider');
const spider=scene.getObjectByName('spider-exhibition');assert(spider?.visible&&hall.visible&&pedestal.visible&&!world.visible,'Spider-Man is a dedicated exhibition');
assert(spider.children.some(o=>o.isInstancedMesh),'city windows are instanced');
select('west');const west=scene.getObjectByName('west-exhibition');assert(west?.visible&&!spider.visible&&!world.visible,'western exhibition isolates city and tundra');
assert(west.children.some(o=>o.geometry?.type==='PlaneGeometry'),'western valley has real terrain');
select('spider');assert.equal(scene.getObjectByName('spider-exhibition'),spider,'revisiting does not rebuild geometry');
for(const group of [spider,west])group.traverse(o=>{if(o.geometry?.attributes.position){for(const v of o.geometry.attributes.position.array)assert(Number.isFinite(v),'finite model geometry');}});
for(const room of ['hall','spider','west']){select(room);setMode('fps');host.canvas.fire('keydown',{key:'w'});frames(600);win.fire('keyup',{key:'w'});assert(camera.position.z>=10.6,'walking cannot enter diorama');assert(Math.abs(camera.position.y-1.35)<.001,'collision preserves eye height');}
select('lobby');setMode('fps');host.canvas.fire('keydown',{key:'w'});frames(500);win.fire('keyup',{key:'w'});assert(camera.position.z>=-7.56,'portal cannot be walked through');
select('west');setMode('cinema');elements.get('#spatial-home-view').fire('click');frames(200);const centered=camera.position.clone();host.canvas.fire('keydown',{key:'a'});frames(40);win.fire('keyup',{key:'a'});elements.get('#spatial-home-view').fire('click');frames(200);assert(camera.position.distanceTo(centered)<.02,'new room standard view resets correctly');
// Resize uses a stable horizontal field in portrait, and caps high-DPI backing pixels.
host.clientWidth=390;host.clientHeight=640;resizeCallback();frames();assert(Math.abs(camera.getFilmWidth()-35)<1e-6,'portrait preserves horizontal composition');assert.equal(camera.aspect,390/640);host.clientWidth=3840;host.clientHeight=2160;resizeCallback();frames();assert(activeRenderer.pixelRatio**2*3840*2160<=3200001,'4K buffers remain within pixel budget');
cleanup();assert(activeRenderer.disposed&&host.canvas.removed&&!dialog.open);assert.equal(revoked,1);console.log(JSON.stringify({stateTransitions:'passed',materialIdentity:'passed',cinemaCenterControls:'passed',firstPersonControls:'passed',modeIsolation:'passed',captureLifecycle:'passed',newExhibitions:'passed',collisionBoundaries:'passed',portraitComposition:'passed',pixelBudget:'passed',webglPixels:'not tested'}));
